# Generated by Django 3.2 on 2021-06-05 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_application_f_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='F_key',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='Marksheet',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='application',
            name='aadhar',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(upload_to='media'),
        ),
    ]
